export {default as Home} from "./Home"
export {default as About} from "./About"
export {default as Users} from "./Users"
export {default as Register} from "./Register"
export {default as UserDetail} from "./UserDetail"